# Generated by Django 3.0.8 on 2020-08-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripus', '0004_auto_20200812_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('visit_date', models.DateField(blank=True)),
                ('website', models.URLField(blank=True, max_length=400)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('approach', models.CharField(blank=True, max_length=800)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('visited', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripus.Trip')),
            ],
        ),
    ]
