# Generated by Django 3.0.8 on 2020-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripus', '0005_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
