# Generated by Django 3.0.8 on 2020-08-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripus', '0006_auto_20200815_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
