# Generated by Django 3.0.8 on 2020-08-20 10:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tripus', '0008_remove_trip_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
