# Generated by Django 3.0.8 on 2020-08-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripus', '0010_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('reservation_number', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='media/tickets/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripus.Trip')),
            ],
        ),
    ]
